name: Marcus P. da Silva
markdown: kramdown
  math-engine: mathjax

theme: jekyll-theme-minimal
permalink: /blog/:year/:month/:day/:title

title: MPS' blog
description: Marcus' blog. Views are my own.

site:
  author: Marcus P. da Silva
