name: Marcus P. da Silva
markdown: kramdown

kramdown:
  math_engine: mathjax

theme: jekyll-theme-minimal
permalink: /blog/:year/:month/:day/:title

title: MPS' blog
description: My name is <a href="https://marcusps.github.io/">Marcus P. da Silva</a>, and this is my blog. It is seldomly updated. The views are my own.
